### ISSUE TITLE
Address Error:Missing required key 'userId' in params

### ISSUE THREAD

**Issue by mikeyqq** [AlexWang-16/react-lex-plus#13]
Issues arises when you enter a request multiples.
It indicates: Error:Missing required key 'userId' in params

**Comment by AlexWang-16** [comment]
I think we need an alternative solution. `lexUserId` keeps changing every time the chat UI is refreshed
<img width="762" alt="Screen Shot 2020-10-07 at 9 05 52 PM" src="https://user-images.githubusercontent.com/13398997/95403723-02a58d80-08e1-11eb-9cb7-f49f55c445ef.png">
