### ISSUE TITLE
Reduce file size upon build.

### ISSUE THREAD

**Issue by mikeyqq** [AlexWang-16/react-lex-plus#16]
The file currently sits on 2.64mb of bundling and build. Will need to address this to optimize file.

**Comment by AlexWang-16** [comment]
Investigated into style-loader and css-loader. Both are necessary to support loading CSS files in the application and cannot be removed. The bundle size is now at 1MB and is as small as possible given what I know. When compiling with `npm run build`, it no longer complains about bundle size.
